# Generated by Django 6.0.1 on 2026-04-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('PREMIUM', 'Premium'), ('VEGETABLE', 'Vegetable')], default='CLASSIC', max_length=20),
        ),
    ]
